# Generated by Django 6.1.1 on 2026-09-15 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneAffectation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=150)),
                ('objectif_beneficiaires', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_campagnes', to=settings.AUTH_USER_MODEL)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation de campagne',
                'verbose_name_plural': 'Affectations de campagnes',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='campagnes_assignees', through='campaigns.CampagneAffectation', through_fields=('campagne', 'agent'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='campagneaffectation',
            constraint=models.UniqueConstraint(fields=('campagne', 'agent'), name='unique_campagne_agent'),
        ),
    ]
