# Generated by Django 6.1.1 on 2026-09-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campagneaffectation_campaign_agents_and_more'),
        ('campaigns', '0002_campaign_statut'),
    ]

    operations = [
    ]
