# Generated by Django 6.1.1 on 2026-09-18 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_merge_20260916_1745'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campagneaffectation',
            name='unique_campagne_agent',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIER', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='campagneaffectation',
            constraint=models.UniqueConstraint(fields=('campagne', 'agent', 'zone'), name='unique_campagne_agent_zone'),
        ),
    ]
