# Generated by Django 6.1.1 on 2026-09-18 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('MENSUEL', 'Mensuel')], default='MENSUEL', max_length=20)),
                ('statut', models.CharField(choices=[('TRIAL', 'Essai gratuit'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='TRIAL', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, default=50000, max_digits=10)),
                ('trial_days', models.PositiveIntegerField(default=7)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscription', to='organizations.organization')),
            ],
            options={
                'db_table': 'payment_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('provider', models.CharField(choices=[('PAYTECH', 'PayTech')], default='PAYTECH', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.subscription')),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_tra_transac_143f1c_idx'), models.Index(fields=['statut'], name='payment_tra_statut_c9ee0f_idx')],
            },
        ),
    ]
