# Generated by Django 6.1.1 on 2026-09-17 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_merge_20260916_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_analyse', models.CharField(choices=[('global', 'Analyse Globale'), ('executive', 'Executive Insight'), ('finance', 'Analyse Financière'), ('zones', 'Analyse Zones')], default='global', max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_analyses', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'ia_ianalyse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campagne', 'type_analyse'], name='ia_ianalyse_campagn_f5ef7c_idx')],
            },
        ),
    ]
