# Generated by Django 6.1.1 on 2026-09-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcriteria_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcriteria',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcriteria',
            name='poids',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectcriteria',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='projects.project'),
        ),
    ]
