# Generated by Django 6.1.1 on 2026-09-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('projects', '0003_alter_projectcriteria_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcriteria',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Question du formulaire liée à ce critère', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria', to='forms.formfield'),
        ),
        migrations.AddField(
            model_name='projectcriteria',
            name='vulnerable_operator',
            field=models.CharField(choices=[('equals', 'Égal à'), ('contains', 'Contient'), ('in', 'Dans la liste'), ('lt', 'Inférieur à'), ('gt', 'Supérieur à')], default='contains', help_text='Opérateur pour évaluer la vulnérabilité', max_length=20),
        ),
        migrations.AddField(
            model_name='projectcriteria',
            name='vulnerable_values',
            field=models.JSONField(blank=True, default=list, help_text="Valeurs considérées comme vulnérables (ex: ['oui', 'true', '1'])"),
        ),
    ]
