"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rix)t5a27riqbsab@f1ls4=3lq-228v&d#5s_=w1#zds%+_qca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
     # Packages
     "rest_framework",
     "rest_framework_simplejwt.token_blacklist",
     "rest_framework_simplejwt",
     "corsheaders",
     "drf_spectacular",

     # Apps BarakaGive360
     "apps.accounts",
     "apps.organizations",
     "apps.projects",
     "apps.zones",
     "apps.campaigns",
     "apps.forms",
     "apps.beneficiaries.apps.BeneficiariesConfig",
     "apps.finance",
       "apps.donors",
        "apps.reports",
        "apps.ia",
        "apps.payment",
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases



DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Dakar"

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom User
AUTH_USER_MODEL = "accounts.User"
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

FRONTEND_URL = "http://localhost:5173"

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BarakaGive360 API",
    "DESCRIPTION": "Documentation des API du backend",
    "VERSION": "1.0.0",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "backend", "backend:8000", "0.0.0.0", "172.18.0.6"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost",
    "http://localhost:80",
    "http://127.0.0.1",
]
CORS_ALLOW_CREDENTIALS = True
# Celery
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Dakar"

CELERY_BEAT_SCHEDULE = {
    "update-campaign-statuses-daily": {
        "task": "apps.campaigns.tasks.update_campaign_statuses",
        "schedule": 86400.0,
    },
    "ia-analyses-every-6-hours": {
        "task": "apps.ia.tasks.run_ia_analyses",
        "schedule": 21600.0,
    },
    "expire-trials-daily": {
        "task": "apps.payment.tasks.expire_trials",
        "schedule": 86400.0,
    },
    "check-expiring-subscriptions-daily": {
        "task": "apps.payment.tasks.check_expiring_subscriptions",
        "schedule": 86400.0,
    },
}

# IA Service
IA_SERVICE_URL = os.getenv("IA_SERVICE_URL", "http://ia_service:8001")

# Email (Brevo API)
# ==========================
# Brevo API
# ==========================

BREVO_API_KEY = os.getenv("BREVO_API_KEY")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# PayTech Payment
# ==========================
PAYTECH_API_KEY = os.getenv("PAYTECH_API_KEY", "")
PAYTECH_API_SECRET = os.getenv("PAYTECH_API_SECRET", "")
PAYTECH_SUCCESS_URL = os.getenv("PAYTECH_SUCCESS_URL", "http://localhost:5173/payment/success")
PAYTECH_CANCEL_URL = os.getenv("PAYTECH_CANCEL_URL", "http://localhost:5173/payment/cancel")
PAYTECH_IPN_URL = os.getenv("PAYTECH_IPN_URL", "http://localhost:8000/api/payment/webhook/")