# Generated by Django 6.1.1 on 2026-09-21 11:20

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0004_remove_campagneaffectation_unique_campagne_agent_and_more'),
        ('organizations', '0004_alter_subscription_options'),
        ('projects', '0004_projectcriteria_question_and_more'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_financement', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('observation', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('APPROUVE', 'Approuvé'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VERIFIE', 'Vérifié'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finance.budget')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depenses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='zones.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('bailleur', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moyen_paiement', models.CharField(choices=[('VIREMENT', 'Virement'), ('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte')], default='VIREMENT', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('observation', models.TextField(blank=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='finance.budget')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dons', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='justifications/')),
                ('type_fichier', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('CONFORME', 'Conforme'), ('A_VERIFIER', 'À vérifier'), ('NON_CONFORME', 'Non conforme')], default='A_VERIFIER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='finance.depense')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
