# Generated by Django 6.1.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EN_ATTENTE_ACTIVATION", "En attente d'activation"),
                    ("ACTIVE", "Actif"),
                    ("SUSPENDED", "Suspendu"),
                ],
                default="EN_ATTENTE",
                max_length=30,
            ),
        ),
    ]
