# Generated by Django 6.1.1 on 2026-09-15 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('local_id', models.UUIDField(db_index=True, help_text='ID local pour synchronisation hors ligne')),
                ('device_id', models.CharField(help_text='Identifiant du dispositif de collecte', max_length=100)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score IA calculé automatiquement', max_digits=5, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'En attente'), ('SYNCED', 'Synchronisé'), ('DUPLICATE', 'Doublon'), ('FAILED', 'Échec')], default='SYNCED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réponse formulaire',
                'verbose_name_plural': 'Réponses formulaires',
                'ordering': ['created_at'],
            },
        ),
    ]
