# Generated by Django 6.1.1 on 2026-09-15 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('organizations', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='zones.zone'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='beneficiaries.beneficiary'),
        ),
    ]
