# Generated by Django 6.1.1 on 2026-09-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='formulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formulaire'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formfield'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['campagne', 'telephone'], name='beneficiari_campagn_76da7b_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['local_id', 'device_id'], name='beneficiari_local_i_eb5e45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('beneficiary', 'question')},
        ),
    ]
