# Generated by Django 6.1.1 on 2026-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_rename_ai_score_beneficiary_score_vulnerabilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='score_vulnerabilite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de vulnérabilité calculé automatiquement', max_digits=5, null=True),
        ),
    ]
