# Generated by Django 6.1.1 on 2026-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Sénégal', max_length=100)),
                ('intervention_domain', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
