# Generated by Django 6.1.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_description_organization_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("ACTIVE", "Active"),
                    ("REJETEE", "Rejetée"),
                    ("SUSPENDED", "Suspendue"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="document_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="organizations/documents/receipts/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="document_ninea",
            field=models.FileField(
                blank=True, null=True, upload_to="organizations/documents/ninea/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="document_statutes",
            field=models.FileField(
                blank=True, null=True, upload_to="organizations/documents/statutes/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Essai gratuit"),
                            ("ACTIVE", "Active"),
                            ("EXPIRE", "Expirée"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("trial_start", models.DateField(blank=True, null=True)),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"verbose_name": "Abonnement", "verbose_name_plural": "Abonnements"},
        ),
    ]
