# Generated by Django 6.1.1 on 2026-09-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_documents_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
    ]
